### ISSUE TITLE
"Cannot get breakpoint location" error

### ISSUE THREAD

**Issue by Moki76** [NicolasPetton/Indium#154]
Hi,

I get the "Cannot get breakpoint location" error when trying to connect to set a breakpoint in a JS script of a fresh React project through the Indium chromium backend.

Here the value of the Chromium response in the `indium-backend-register-breakpoint)` function : 
> ((id . 12) (result (breakpointId . "1:42:0:f:/Travail/Temp/web_app_test/src/App.js") (locations . [])))

I have modified webpack configuration according to these 2 lines as said in the documentation : 
`devtoolModuleFilenameTemplate: '[absolute-resource-path]',`
`devtoolFallbackModuleFilenameTemplate: '[absolute-resource-path]?[hash]'`

Parsing sources files seems to occur without errors : 
> Parsing sourcemap...
> Parsing sourcemap ...done!

Note that I get another error that may or may not be related to this issue. When connecting to Chromium tab (http://localhost:3000) in `indium-v8--handle-ws-open` function (probably on the first instruction, but I failed to find where this message come from...) : 
> Invalid parameters

My environment : 
- Windows 8.1
- Emacs 25.2.1
- Indium package 20180521.1355
- Chromium 63.0.3239.108

Thank you in advance for your help.

**Comment by NicolasPetton** [comment]
Thanks for reporting this issue!

Sourcemap support is still in its infancy, this will definitely help me improve it (especially on Windows).

Could you tell me how you created your React project, and if you have made any changes to it after its creation?

Thanks

**Comment by Moki76** [comment]
Thank you for your prompt reply.

I'm learning Web developpement and I have followed [that tutorial ](https://openclassrooms.com/courses/realisez-une-application-web-avec-react-js) which simply makes use of the _create-react-app_ package.

Here is the path of the default Webpack configuration used by React that I tried to modify (but I get the same error with or without any change) : _node_modules\react-scripts\config\webpack.config.dev.js_

**Comment by NicolasPetton** [comment]
Thanks, that's helpful! I'll try to debug it and will get back to you!

**Comment by Moki76** [comment]
Thanks for your feedback. Do you plan to fix it soon ?

**Comment by NicolasPetton** [comment]
Moki76 <notifications@github.com> writes:

> Thanks for your feedback. Do you plan to fix it soon ?

Yes, I'm working on sourcemap improvements, and I expect to have a fix
in master within a couple of weeks.

**Comment by Moki76** [comment]
Ok good news !

**Comment by NicolasPetton** [comment]
The settings and sourcemap refactorings have landed in master.

Could you read the docs https://indium.readthedocs.io/en/latest/setup.html and give it a try?

**Comment by Moki76** [comment]
Thanks, I'am going to test it as soon as possible.

**Comment by karta0807913** [comment]
this is my .indium.json file
```
{
    "configurations": [
        {
            "type": "node",
            "root": "src"
        }, {
            "name" : "LogServer",
            "type" : "node",
            "command" : "node src/server.js",
            "inspect-brk": true
        }, {
            "name" : "LogClient",
            "type" : "chrome",
            "host" : "127.0.0.1",
            "url"  : "http://127.0.0.1:9000/login",
            "port" : 9222
        }
    ]
}
```

and run 

in command line
```
node --inspect=9229 src/server.js
```

in emacs 
```
M-x indium-connect
```

have another error
error in process fitter: Invalid status code from server

my system is windows 10

by the way
I can't connect to chrome when I run 
`M-x indium-launch`

**Comment by NicolasPetton** [comment]
Hi! 

The new version on master (which has a lot of changes, see here https://emacs.cafe/emacs/javascript/indium/2018/08/14/indium.html) should fix the issue.

**Comment by Moki76** [comment]
Hi,

I have tested the Indium new release, sorry for not having done it ealier.

Unfortunately it still doesn't work for me, but maybe I have missed something as Indium way of configuration has changed recently.

Here is the steps I followed :
- update emacs indium package with melpa
- install indium server with npm
- create a fresh React app : `create_react_app web_app_test`
- add .indium.json configuration file in the root folder (`web_app_test`) :
```{
  "configurations": [
    {
      "name": "web_app_test",
      "type": "chrome",
      "root": "src",
      "host": "localhost",
      "url": "http://localhost:3000",
      "port": 9222
    }
  ]
}
````
- start the app with `yarn start`
- start Indium with `M-x indium-launch`
- add de breakpoint in src/App.js line 8
- use Chrome refresh button to reload the page

The breakpoint is never fired.
If I add the same breakpoint through the Chrome dev tool, this one is fired in the Chrome interface and also in Indium. So maybe setting the breakpoint through Indium failed silently...

Note that I am under Windows.

Thank you in advance for your help.

**Comment by NicolasPetton** [comment]
I'm reopening the issue.

I'll try to reproduce using the exact same steps on Windows.

**Comment by NicolasPetton** [comment]
One question though, is the breakpoint ever resolved (the icon becomes a plain red circle as opposed to a shallow red circle)?

**Comment by Moki76** [comment]
Thanks. No the breakpoint should not be resolved as the red circle never becomes plain.

**Comment by NicolasPetton** [comment]
@Moki76 I have tested the latest master with the latest npm package under windows 10 with the provided steps, and it works fine now for me in Windows.

If it's still an issue for you, please tell me and reopen the issue.

**Comment by Moki76** [comment]
@NicolasPetton , I confirm that updating to the last version of Indium in Melpa (20181126.2048) fixes the bug.
Good job, thank you !
